### PR TITLE
Add dark scheme support by switching to bootstrap-dark

### LINKED ISSUE #5: Please consider respecting dark theme preference
It should be pretty simple using the `prefers-color-scheme` media selector: 
```css
@media (prefers-color-scheme: dark) { /* ... */ }
```

[Here's an example](https://github.com/mozilla/multi-account-containers/blob/682d877960ced0826d1a8def540bdd5e252b9192/src/css/options.css) of it being used in the official multi-account-containers addon CSS.

### PR DESCRIPTION
**Pull request by KerfuffleV2**
This commit switches to using bootstrap-dark from https://github.com/vinorodrigues/bootstrap-dark

The license is the same as Bootstrap so that shouldn't create an issue.

Notes:

1. This also upgrades from Bootstrap 4.5.3 to 4.6.0 - as far as I can tell it didn't cause problems.
2. If you don't plan on actually editing the Bootstrap CSS itself, it may be better to use the minified CSS and associated `.map` file. I used the normal one because that's what currently existed in your repo. Links [here](https://github.com/vinorodrigues/bootstrap-dark#CDN) but I could also update the pull request if you prefer.
3. I didn't do extensive testing in light mode, I'm just assuming it works because I'm kind of a lazy jerk.

Closes #5

### CODE REVIEW

**Comment by charles-m-knox** [comment]
Hey @KerfuffleV2 thanks a TON for making this PR! I'm going to spin up a test profile and validate this today.

**Review by charles-m-knox — APPROVED** [review]
As a security precaution, the sha256 sum of the official latest release (https://github.com/vinorodrigues/bootstrap-dark/releases/tag/v0.0.9) of the files `dist/bootstrap-dark.css*` are:

```
3593f8eea424a9ef81bed07e080ac996fa653ab12b8bd4d0a0860305289db487  bootstrap-dark.css
c0e9912e9e21ca92ac6a67f3af9ce8d837b29ee0d9fc3e2c7d79d2bccf5a07e1  bootstrap-dark.css.map
```

And on @KerfuffleV2's branch, the sha256 sums are:

```
3593f8eea424a9ef81bed07e080ac996fa653ab12b8bd4d0a0860305289db487  bootstrap-dark.css
c0e9912e9e21ca92ac6a67f3af9ce8d837b29ee0d9fc3e2c7d79d2bccf5a07e1  bootstrap-dark.css.map
```

They appear to match, indicating that the CSS blobs in these two files are indeed from the upstream source directly. :+1: 

Additionally, I have tested this extension on Ubuntu 20.04 with Firefox in both light mode and dark mode, and the theme appears to only have been altered slightly, but the theme _is_ correctly respected. Nicely done!

Lastly, from a technical debt perspective, I believe that it is not a good long-term move to use https://github.com/vinorodrigues/bootstrap-dark, because this repository is small (52 stars, compared to something like Bootswatch which has 12k stars and 3.4k forks), and the author explicitly states that this is a project he/she/they did as a learning effort. In an ideal world, I'd like to simply drop-in two widely distributed bootstrap CSS distributions (one for light, and one for dark) and have the theming switch between the two based on addon preference. However, I don't currently have the time to dedicate to figuring that one out... so this is a happy medium! We can probably safely use this distribution for at least 1-2 years without any worry, possibly even longer :)

---

With all that being said, thank you again for this work @KerfuffleV2! I will try and tackle one or two of the other GitHub issues created by a few other folks before I do a release that contains this dark mode, I especially want to fix #4.

P.S. @KerfuffleV2  if you want to keep in touch outside of GitHub PR's, I've been contemplating creating a Slack workspace or a Discord server so I can keep in touch with the community and share ideas about the extension. Is this something you'd be interested in? If so, which platform? If not, I can post on Twitter instead (see the link on https://charlesmknox.com) and engage there.

**Comment by charles-m-knox** [comment]
https://twitter.com/charlesmknox/status/1372278989755060224 I thanked you here!

**Comment by KerfuffleV2** [comment]
@charles-m-knox Glad it turned out to be helpful for you! I agree it's probably not the best long term solution but it really shouldn't be too bad for technical debt - reverting to normal Bootstrap is something that can be done in a minute or two and you won't be worse off than before!

That said, if you actually _have_ a dark version of Bootstrap that you want to use and you'd prefer to do it the two separate `.css` files way that should be pretty easy. Example:

```javascript
const dark_please = window.matchMedia('(prefers-color-scheme: dark)').matches;
if (dark_please) {
  // inject dark CSS here
} else {
 // inject normal CSS here
}
```

Since your addon is already Javascript and you know you're running in Firefox you don't have to do any of the song and dance to check that the function is available and handle the case where it isn't. I won't be disappointed if you don't use my change, and of course it was super-trivial so no work of consequence will be lost.

***

About the last part - I know it probably feels kind of bad to get a response like this but I am honestly completely horrible about staying in touch with people I actually _need_ to. As an asocial bastard, I'm not likely to take you or anyone else up on an offer like that. It's definitely not you, it's me. Sorry!

**Pull request merged**
